### ISSUE TITLE
iPhone 11 above doesn't support hapticFeedback

### ISSUE THREAD

**Issue by thidayatullah** [iSapozhnik/Haptico#14]
Maybe it's because on `UIDevice+Extensions` it only checks up to iPhone XS Max.

```internal var hasTapticEngine: Bool {
        get {
            return deviceType == .iPhone6S || deviceType == .iPhone6SPlus ||
                deviceType == .iPhone7 || deviceType == .iPhone7Plus ||
                deviceType == .iPhone8 || deviceType == .iPhone8Plus ||
                deviceType == .iPhoneX || deviceType == .iPhoneXR ||
                deviceType == .iPhoneXS || deviceType == .iPhoneXSMax

        }```

I said maybe because I don't have iPhone 11 device so I'm not sure if adding iPhone 11 checking will solve the problem.

**Comment by justinkumpe** [comment]
I was going to submit a pull request for this as I noticed it today as well but it appears this has already been resolved in the GitHub code. But the CocoaPod was not updated. So we just need someone to push the new code to cocoapods. @iSapozhnik can you push the updated code as a new version to CocoaPods please?

**Comment by justinkumpe** [comment]
@thidayatullah in the mean time import your cocoa pod as follows. this will update to 1.1.0 which I have confirmed works with iPhone 11 models

`pod 'Haptico', :git => 'https://github.com/iSapozhnik/Haptico.git', :branch => 'master'`
